### ISSUE TITLE
CustomValidators.date does not work correctly in Safari.

### ISSUE THREAD

**Issue by Tolitech** [rsaenen/ngx-custom-validators#11]
Validation works correctly in Chrome, Firefox, Opera, IE, Edge.
However, any valid date is indicated as "invalid" in Safari.

"@angular/core": "^6.0.0",
"ngx-custom-validators": "^6.0.0"

Form Group:
initialDate: [this.item.initialDate, [CustomValidators.date]]

**Comment by rsaenen** [comment]
As I have not a Mac, I won't be able to close this issue.
A PR is needed.

**Comment by Tolitech** [comment]
Unfortunately I do not have it either.
I tested it on the ipad.
let's wait...

**Comment by rsaenen** [comment]
That could be an issue specific to iOS. I’ll check with Stackblitz in a Apple Store...

**Comment by rsaenen** [comment]
Released with 6.0.4, can you confirm the fix?

**Comment by Tolitech** [comment]
I had to change some components to work together.
It works.
Thank you very much.

https://angular-blnggz.stackblitz.io/

**Comment by rsaenen** [comment]
The fix has been released with 6.0.5.
6.0.4 has still a bug with Safari OS X and iOS.

FYI, "2018-8-20" is not a valid date but "2018-08-20" is. That was the mistake
