### ISSUE TITLE
Validate All

### ISSUE THREAD

**Issue by srabanicn** [rsaenen/ngx-custom-validators#13]
Hi,

I need to check whether all the input fields are valid or not on Submit button. So I need a `validateAll()` or something like this. Is there any way to achieve this?

Please suggest.

 Thanks.

**Comment by rsaenen** [comment]
Hi,
I'm sorry but this is not an issue. You should check Angular Guide:
* [Forms](https://angular.io/guide/forms)
* [Form Validation](https://angular.io/guide/form-validation)
* [Reactive Forms] (https://angular.io/guide/reactive-forms) 

What you ask is a native feature from Angular.
