### ISSUE TITLE
Can't bind to 'validator' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by woj1965** [rsaenen/ngx-custom-validators#14]
**IMPORTANT:**
Hello, I already import 
**import { CustomFormsModule } from 'ngx-custom-validators'; at app.module.**
But I get the issue **Can't bind to 'validator' since it isn't a known property of 'input'.**

I don't know what else I need to do, I using Angular 5 and start learning a few weeks ago.

**Current behavior**

  - unknown property of 'input'.

**Expected/desired behavior**

  - Accept [validator] as input property

**Environment information**

  - OS: MacOSx 10.14
  - Angular Version: 5.2.4
  - Typescript version: 2.4.2
  - npm version: 6.4.1
  - Node Version: 10.6.0

**Other information**

**Comment by rsaenen** [comment]
Hi,
Which validator did you use for this test?

Don't forget to import FormsModule from @angular/forms

**Comment by woj1965** [comment]
Hi, I have tried all with braces, mainly [equal], [gte], [equalTo], [notEqualTo], [rangeLength] and others.

I imported FormsModule before CustomFormsModule.

**Comment by rsaenen** [comment]
Please use this Stackblitz to show your error:
https://stackblitz.com/edit/angular-rlku8h?file=src%2Fapp%2Fapp.component.html

**Comment by woj1965** [comment]
I was tested using Stackblitz you suggested and works fine.
And I try to use some other modules (Angular material), and components at Stackblitz, works too.
Maybe the problems is in another packages I installed, I don't know.
My experience in Angular is too fresh, so if you have some tip where I can start please tell me.
Thanks for your attention.

**Comment by rsaenen** [comment]
You should create a shared module which import and export the CustomFormsModule.
Others module has to import that shared module.
