### ISSUE TITLE
7.0.0 is not released on npm

### ISSUE THREAD

**Issue by danielsogl** [rsaenen/ngx-custom-validators#17]
Hey, I noticed you release v7 with Angular 7 support but it looks like you forgot to release it on npm.

**Comment by rsaenen** [comment]
Hey, I checked and v7.0.0 is released on npm.
Can you try `npm i ngx-custom-validators@7.0.0` ?

**Comment by danielsogl** [comment]
Maybe I clicked on the wrong link.
