### ISSUE TITLE
minDate validation with year < 100

### ISSUE THREAD

**Issue by meraj-ahmed** [rsaenen/ngx-custom-validators#18]
When I use something like `minDate="1900-01-01"`, it fails to properly catch a date input with a year between 0 and 99. For example, if you input `0001-01-01`. If I understand this correctly, it appears it could be a possible issue with parseDate:

https://github.com/rsaenen/ngx-custom-validators/blob/master/src/app/util/lang.ts#L14

It may need to properly account for the way JS handles years 0-99 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Two_digit_years_map_to_1900_-_1999)

Is this a valid bug?

**Comment by rsaenen** [comment]
Could you use a Stackblitz for example?
I'm not sure to understand this issue.

Function parseDate has to provide a support for Moment, NgBootstrap and a polyfill (as Safari doesn't parse date like other browser).

With an input like `minDate="1900-01-01"`, parseDate() do nothing and returns the string that will be parsed by `new Date()`.

For now, I can only recommand using of Moment

**Comment by kktos** [comment]
Ralf,

could it be possible you test the existence of some date libraries and use it ?
Like momentjs or even better (as lighter) date-fns ?

Cheers mate ;)

/tm
