### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by YZahringer** [rsaenen/ngx-custom-validators#22]
When updating Angular to version 8.0.0, the following warnings are generated:
````
npm WARN ngx-custom-validators@7.0.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN ngx-custom-validators@7.0.0 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
````

**Comment by DmitryEfimenko** [comment]
also please make sure it works with ivy. The original repository which this one is forked from was returning this error: https://github.com/angular/angular/issues/29564

**Comment by rsaenen** [comment]
No worries, I will release version 8.0.0 asap.

This package use a clean angular app, ng-packagr and follows guidelines.

**Comment by rsaenen** [comment]
Released.
