### ISSUE TITLE
[Feature request] Validator to check if a value is included (or not) in an array

### ISSUE THREAD

**Issue by beradrian** [rsaenen/ngx-custom-validators#42]
It would be nice to have a validator to check if the control value is included or not in an array, something like [includedIn]="array" or [notIncludedIn]="array". The second one will be useful to check the uniqueness of a value.
If interested I can submit a PR.

**Comment by rsaenen** [comment]
I recommand you to check #37 

As long as a validators comes with testing, I can merge it, thanks.

**Comment by beradrian** [comment]
https://github.com/rsaenen/ngx-custom-validators/pull/43

**Comment by beradrian** [comment]
PR #43 was merged.
