### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'error': 'null'

### ISSUE THREAD

**Issue by bude10** [rsaenen/ngx-custom-validators#44]
**IMPORTANT:**
Actually, this is a well known issue in Angular. In the past to call manually the **ChangeDetectorRef** in ngAfterViewInit helped. But this time it's more tricky. Because the input-field is nested in a *ngIf.

**Steps to reproduce and a minimal demo**

This is used in an angular material dialog:

`
<mat-dialog-content>
  <dnd-file-chooser
    *ngIf="!file"
    (change)="select($event.detail)">
  </dnd-file-chooser>
  <div *ngIf="file">
    <h6>filename</h6>
    <text-field
      #titleModel="ngModel"
      [(ngModel)]="title"
      [error]="titleModel.errors"
      required>
    </text-field>
    <status-text error [hidden]="!titleModel.errors | async">
      {{ 'app.create.error.required' | translate }}
    </status-text>
  </div>
</mat-dialog-content>
<mat-dialog-actions>
  <button
    [disabled]="!file || titleModel.errors"
    (click)="addResource()">
      Submit
  </button>
</mat-dialog-actions>
`

**Current behavior**

  - After file is selected, the file-choose disappears and the choosen file is displayed and a text-field for changing its name
  - In this moment the error is thrown.

**Expected/desired behavior**

  - The error shouldn't be thrown. 

**Environment information**

  - Angular Version: 10.1.6
  - Typescript version: 4.0.3
  - npm version: 6.13.4
  - Node Version: 12

**Comment by bude10** [comment]
Actually the code example isn't displayed correctly. Therefore I post a screenshot from it:
![image](https://user-images.githubusercontent.com/64399244/96545242-4ff20980-12a8-11eb-9d80-f808645b261e.png)

**Comment by rsaenen** [comment]
Hi,
I'm sorry but I think this issue is not related to `ngx-custom-validators`.

`required` is a native Angular validator, you should provide a stackblitz example to get help.
Moreover, this question belongs more to Stackoverflow.

**Comment by bude10** [comment]
thanks for your response!
