### ISSUE TITLE
Angular 11 Update

### ISSUE THREAD

**Issue by mreouven** [rsaenen/ngx-custom-validators#49]
Types of parameters 'control' and 'control' are incompatible.
    Type 'import("node_modules/@angular/forms/forms").AbstractControl' is not assignable to type 'import("node_modules/ngx-custom-validators/node_modules/@angular/forms/forms").AbstractControl'.
      Types have separate declarations of a private property '_parent'.

  - OS: 
  - Angular Version: 11.0.0
  - Typescript version: 4.0.3
  - npm version: 6.0.1
  - Node Version: 14

**Other information**

**Comment by lneninger** [comment]
Same here. There is any workaround for this?

**Comment by sannyjacobsson** [comment]
## Downgrade ngx-custom-validators
update your package.json 
`"ngx-custom-validators": "8.0.0"` 

run
`npm install ngx-custom-validators --force --no-save` 

## Upgrade Angular to v 11 from previous versions
If anyone else have issues upgrading from previous versions of Angular using ng update 
`ng update @angular/core @angular/cli`  
and getting errors indicating that _**ngx-custom-validators**_ require earlier versions of angular/core. You can upgrade _**ngx-custom-validators**_ to latest version. Upgrade angular and after that downgrade _**ngx-custom-validators**_ to version 8
