### ISSUE TITLE
v11 Publish Issue

### ISSUE THREAD

**Issue by exequiel09** [rsaenen/ngx-custom-validators#51]
Hi I think you published the wrong contents to NPM. I think you published the whole source instead of the compiled distributable version of it.

![Screen Shot 2020-12-14 at 8 54 21 AM](https://user-images.githubusercontent.com/1289472/102029632-23f78e00-3dea-11eb-8bfc-dbfbdc736b4e.png)

**Comment by rsaenen** [comment]
This should be ok

**Comment by exequiel09** [comment]
Closing. Already working. Thanks!
![Screen Shot 2020-12-14 at 6 43 15 PM](https://user-images.githubusercontent.com/1289472/102072013-3bf7fd80-3e3c-11eb-8c05-d5e15da4e8bd.png)
